version: '3.8'

services:

  server:
    build: ./server
    ports: 
      - 8080:8080
    volumes:
      - ./server:/server
    depends_on:
      - db

  attacker:
    build: ./attacker
    ports: 
      - 8081:8080
    volumes:
      - ./attacker:/server
      
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    expose:
      - 3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d